### ISSUE TITLE
v4.0.0 Release Checklist

### ISSUE THREAD

**Issue by brettchalupa** [brettchalupa/graphql-docs#122]
Little things to do to prepare for cutting the new release once the work is done:

- [x] run off of the latest commits in `main` for a bit and see how it goes
- [x] explore doing a pre-release gem
- [x] make a decision on whether or not to keep using dartsass or remove the need for sass altogether
- [x] test the CLI quite a bit to ensure it's working properly
